In [1]:
import numpy as np 
import pandas as pd

In [6]:
np.random.seed(23)

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample, columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample, columns=['feature1','feature2','feature3'])
df1['target'] = 0

combined_df = pd.concat([df,df1],ignore_index=True)

combined_df = combined_df.sample(40)
combined_df.head()

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [8]:
mdf = combined_df

In [12]:
import plotly.express as px

In [15]:


# y_train_trf = y_train.astype(str)
fig = px.scatter_3d(mdf, x='feature1', y='feature2', z='feature3',
                    color=mdf['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='grey')),
                  selector=dict(mode='markers'))


ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'color=1<br>feature1=%{x}<br>feature2=%{y}<br>feature3=%{z}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#636efa', 'line': {'color': 'grey', 'width': 2}, 'size': 12, 'symbol': 'circle'},
              'mode': 'markers',
              'name': '1',
              'scene': 'scene',
              'showlegend': True,
              'type': 'scatter3d',
              'x': {'bdata': ('NH+biOiF179B9VhOe+vaP3UXmWq1fv' ... '5vFJe/FZ26DqZG9D+1VBZ/K1v8Pw=='),
                    'dtype': 'f8'},
              'y': {'bdata': ('kOrC7ggz8r8NGQXo+VfaP0/7V7d6h+' ... 'MgfYs/kwOAlKA5xj/B9siixDzWvw=='),
                    'dtype': 'f8'},
              'z': {'bdata': ('Gz4gKYQn9b9TmEbkSEKyv6yJIWPLve' ... 'RC8+0/JVQemXOS87/dI2zIyXHlPw=='),
                    'dtype': 'f8'}},
             {'hovertemplate': 'color=0<br>feature1=%{x}<br>feature2=%{y}<br>feature3=%{z}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#EF553B', 'line': {'color': 'grey', 'width': 2}, 'size': 12, 'symbol': 'circle'},
              'mode': 'markers',
              'name': '0',
              'scene': 'scene',
              'showlegend': True,
              'type': 'scatter3d',
              'x': {'bdata': ('cB4YBfKpxj8RrEKwX832P4T5z06iyw' ... '2JMco/UuE+sp725z+n98TRC77zPw=='),
                    'dtype': 'f8'},
              'y': {'bdata': ('JvSht7Uj47+/Yffh9A73P0iE1ULHfc' ... 'XDn4e/1LzUyLC+BEBwf5DSqAWrPw=='),
                    'dtype': 'f8'},
              'z': {'bdata': ('y9Aoxsqf8z/c2FLsJV7HP0lFrBXsEv' ... '3MNAlA+CcZWau78j+AkGAiqr3Qvw=='),
                    'dtype': 'f8'}}],
    'layout': {'legend': {'title': {'text': 'color'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'scene': {'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
                         'xaxis': {'title': {'text': 'feature1'}},
                         'yaxis': {'title': {'text': 'feature2'}},
                         'zaxis': {'title': {'text': 'feature3'}}},
               'template': '...'}
})

In [ ]:
# step1 mean standarding

from sklearn.preprocessing import StandardScaler 
s1 = StandardScaler()

df.iloc[:,0:3] = s1.fit_transform(df.iloc[:,0:3])

# step2 finding Covariance matrix
covariance_matric = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print(covariance_matric)


[[ 1.05263158  0.20397591 -0.28888004]
 [ 0.20397591  1.05263158  0.10956124]
 [-0.28888004  0.10956124  1.05263158]]


In [18]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matric)

eigen_values

array([0.64212617, 1.36120658, 1.15456198])

In [19]:
eigen_vectors

array([[-0.65172443,  0.74834128,  0.12345283],
       [ 0.48046517,  0.28140349,  0.8306415 ],
       [-0.58686326, -0.60066414,  0.54294945]])